language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
 - pecl install -f redis-2.2.8
 - sh .travis-ci/init.sh
 - composer self-update
 - composer update
 - php -i | grep redis

script:
  - sleep 10 && phpunit -v --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
